export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const FETCH_USER_POSTS_START = 'FETCH_POSTS_USER_START';
export const FETCH_USER_POSTS_SUCCESS = 'FETCH_POSTS_USER_SUCCESS';
export const FETCH_USER_POSTS_FAIL = 'FETCH_POSTS_USER_FAIL';

export const DELETE_USER_POST = 'DELETE_USER_POST';
export const DELETE_USER_POST_START = 'DELETE_USER_POST_START';
export const DELETE_USER_POST_SUCCESS = 'DELETE_USER_POST_SUCCESS';
export const DELETE_USER_POST_FAIL = 'DELETE_USER_POST_FAIL';

export const ADD_USER_POST = 'ADD_USER_POST';
export const ADD_USER_POST_START = 'ADD_USER_POST_START';
export const ADD_USER_POST_SUCCESS = 'ADD_USER_POST_SUCCESS';
export const ADD_USER_POST_FAIL = 'ADD_USER_POST_FAIL';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_START = 'ADD_COMMENT_START';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const CLEAR_COMMENTS_LOADED = 'CLEAR_COMMENTS_LOADED';